name: Code quality

on:
  push:
    branches:
      - main
      - dev
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
      name: ⬣ Lint repo
    runs-on: ubuntu-latest
      permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .


# name: ⬣ Lint repository

# on:
#   push:
#     branches:
#       - main
#       - dev
#   pull_request:

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

# jobs:
#   lint:
#     name: ⬣ Lint repo
#     runs-on: ubuntu-latest
#     steps:
#       - name: ⬇️ Checkout repo
#         uses: actions/checkout@v4

#       - name: ⎔ Setup node
#         uses: actions/setup-node@v4
#         with:
#           cache: npm
#           cache-dependency-path: ./package.json
#           node-version: 18

#       - name: 📥 Install deps
#         run: npm install

#       - name: 🔬 Lint
#         run: npm run lint
